# Q1. Pandas version
#### What's the version of Pandas that you installed?

In [81]:
import pandas as pd
pd.__version__


'2.2.2'

# Q2. Records count
#### How many records are in the dataset?

In [82]:
df = pd.read_csv('laptops.txt', sep=',')

df.shape

(2160, 12)

# Q3. Laptop brands
#### How many laptop brands are presented in the dataset?

In [83]:
len(set(df["Brand"].to_list()))

27

# Q4. Missing values
#### How many columns in the dataset have missing values?

In [84]:
for x in df.columns.tolist():
    print(df[x].isna().sum())

0
0
0
0
0
0
0
42
1371
4
0
0


# Q5. Maximum final price

In [85]:
filtered_df = df[df['Brand'] == "Dell"]
filtered_df["Final Price"].max()

3936.0

# Q6. Median value of Screen


#### 1. Find the median value of Screen column in the dataset.


In [86]:
df['Screen'].median()

15.6

#### 2. Next, calculate the most frequent value of the same Screen column.

In [87]:
df['Screen'].mode()[0]

15.6

#### 3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

In [88]:
newdf = df.fillna(15.6)

#### 4. Now, calculate the median value of Screen once again.


In [89]:
newdf["Screen"].median()

15.6

#### Has it changed?

#### No, it is the same

# Q7. Sum of weights

#### 1. Select all the "Innjoo" laptops from the dataset.

In [90]:
filtered_df = df[df['Brand'] == "Innjoo"]


#### 2. Select only columns RAM, Storage, Screen.

In [91]:
filtered2_df=filtered_df[["RAM", "Storage", "Screen"]].copy()
filtered2_df

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

### 3. Get the underlying NumPy array. Let's call it X.

In [92]:
X=filtered2_df.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

#### 4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.


In [93]:
import numpy as np
XTX=X.T@X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

#### 5. Compute the inverse of XTX.

In [94]:
inverse_matrix = np.linalg.inv(XTX)
inverse_matrix

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

#### 6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].


In [95]:
y=np.array([1100, 1300, 800, 900, 1000, 1100])

#### 7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [96]:
w=(inverse_matrix@X.T)@y
w

array([45.58076606,  0.42783519, 45.29127938])

#### 8. What's the sum of all the elements of the result?

In [97]:
w.sum()

91.2998806299555